# Generated by Django 4.2.7 on 2025-07-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(choices=[('Staff', 'Staff'), ('Student', 'Student'), ('Contractor', 'Contractor'), ('Others', 'Others')], max_length=50)),
                ('services_requested', models.TextField(blank=True)),
                ('rating', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Very Good', 'Very Good'), ('Fair', 'Fair')], max_length=20)),
                ('complaint', models.TextField(blank=True)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('staff_name', models.CharField(blank=True, max_length=255)),
                ('suggestions', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('feedback_satisfaction', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Very Good', 'Very Good'), ('Fair/Poor', 'Fair/Poor')], max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
